### ISSUE TITLE
Page not loading the javascript and css files needed for it to work

### ISSUE THREAD

**Issue by gnapse** [TinkerDev/grape-swagger-rails#1]
I have this gem installed in my app, and when I visit the documentation page this is what I get.

![error](https://cloud.githubusercontent.com/assets/15199/5970690/585e0352-a815-11e4-9009-e6e24d54c15d.png)

In the console is evidenced that the web page is not being able to load the css and js needed for it to work. Any ideas on why I'm getting this?

**Comment by dblock** [comment]
Do other assets in your application work? Looks like the assets from grape-swagger-rails aren't getting included in the asset pipeline. If you put the project up will be glad to help. 

Generally you have to have `*= require_tree .` in your application.css and `//= require_tree .` in your application.js and that's it.

**Comment by gnapse** [comment]
Well, now that you mention it, my app was generated with [rails-api](https://github.com/rails-api/rails-api), and it is possible that it has all the asset pipeline disabled or not loaded at all, because none of it is normally needed for an api-only kind of app. However, it's curious that nobody has reported this problem before, because grape is for APIs, and it should be common for someone to try to combine them both. The API works fine though, it's only the documentation part that has this problem. I'll check it out and see if I can re-enable the asset pipeline, if that's the problem.

**Comment by dblock** [comment]
I would be interested in instructions on how to integrate this without asset pipeline, or maybe how to turn just the parts needed on top of a Rails API project, or something like that.

**Comment by rjocoleman** [comment]
Came across this today too. I elected just to use sprockets/asset pipeline. You could look at rake-pipeline but it's not looking super maintained right now.

Here's how:

1. Make sure sprockets is a thing in your app, `rails-api` comes with ActionPack so it's just a simple require.

```ruby
# config/application.rb
require 'sprockets/railtie' # OR require 'rails/all'
```
2. Minimum CSS and JS:
```javascript
// app/assets/javascripts/application.js
//= require_tree .
```
```css
/* app/assets/stylesheets/application.css
*= require_tree .
*/
```

From there `grape-swagger-rails` works for me!

**Comment by gnapse** [comment]
Yes, that solves it. Thanks @rjocoleman!

**Comment by dblock** [comment]
@rjocoleman Can you please contribute this to the README and maybe put up a sample project?

**Comment by dapicester** [comment]
I came across this today on a Rails application.
In my case the `grape_swagger_rails/application.css` and `grape_swagger_rails/application.js` were not there when deploying to production.
So I solved with `rake assets:precompile` on production environment.

**Comment by JacobGalati** [comment]
For anyone looking at this many many years later. I had to add `gem "propshaft"` to my Gemfile to get it workng.
