### ISSUE TITLE
Rails can't find assets on Production env

### ISSUE THREAD

**Issue by pablocrivella** [TinkerDev/grape-swagger-rails#10]
Do i need to do something to make this work on production or staging?

Now i get this error:

![screen shot 2015-03-31 at 17 54 29](https://cloud.githubusercontent.com/assets/1854923/6930202/150da758-d7cf-11e4-84a7-b5a5f561263c.png)

**Comment by pablocrivella** [comment]
nevermind, i solved it.. sorry for spaming :sweat_smile:

**Comment by dblock** [comment]
Please do tell us how you solved it. Maybe we need a README update?

**Comment by pablocrivella** [comment]
We'll the error i was getting was because i was deploying to a staging env, but i didn't have a ```staging.rb``` on ```config/environments```, so i gues it was defaulting to ```development.rb```.
Other error i found is that you need to add ```rack-cors``` middleware and configure it to make swagger work with your api.
