### ISSUE TITLE
Add ability to namespace request URLs

### ISSUE THREAD

**Issue by mini-thor** [TinkerDev/grape-swagger-rails#19]
Is there a way to namespace request routes generated by `Grape::API` endpoints?

I am using grape and grape-swagger-rails inside a rails engine and the URLs generated in the swagger UI don't include that namespace.

Ex.
My engine is called `BlogManager` an my routes file looks like this:

`mount GrapeSwaggerRails::Engine, at: "/documentation"`

The problem is that in the UI the generated URLs look like these:

- `/api/v1/tags` (GET)
- `/api/v1/tags` (POST)

which don't have the namespace `/blog_manager` and the `try it out button` obviously fail.

**Comment by dblock** [comment]
The URLs should include the namespace. You should bring this up on the Grape mailing list or open an issue with a repro in grape-swagger.
