### ISSUE TITLE
Make googlefonts optional

### ISSUE THREAD

**Issue by calfzhou** [TinkerDev/grape-swagger-rails#4]
Thanks for this great tool!

Is it possible to add an option to disable google font? There are some places in the world hard to access google service :crying_cat_face:

**Comment by calfzhou** [comment]
I created a custom index.html.erb to overwrite the default one.

**Comment by dblock** [comment]
Yes, that works. Generally we would welcome some refactoring of that ERB into helpers and what not to make it easier to customize.
