### ISSUE TITLE
Paths with grape-swagger-rails 0.9

### ISSUE THREAD

**Issue by adamlove127** [TinkerDev/grape-swagger-rails#7]
With previous applications running 0.7.2, I would initialise with
`GrapeSwaggerRails.options.url      = '/swagger_doc.json'`

However, with v 0.9, had to replace that with 
`GrapeSwaggerRails.options.url      = '/swagger_doc'`
and remove the .json to get things to work

**Comment by dblock** [comment]
That is correct, and documented in Grape's UPGRADING.
