### ISSUE TITLE
Grape 0.10.1 and 0.11.0

### ISSUE THREAD

**Issue by ristovskiv** [TinkerDev/grape-swagger-rails#8]
Will this be available for the newest versions of Grape?

**Comment by dblock** [comment]
The latest version works with Grape 0.10.1 and 0.11.0.

**Comment by ristovskiv** [comment]
Sorry for bothering you it worked, just needed grape-swagger 0.9.0. One more question how to specify the version of the api. Let's say the api_url is http://localhost:3000/api/v1/users.json? It works without the version /api/users.json, but I can't figure out a way with the api version.

**Comment by dblock** [comment]
Describe "it doesn't work"? You should put up a demo project with the issue related to version and open an issue here.

**Comment by ristovskiv** [comment]
I've figure this out as well, just used the "api_version" key of the the hash that is passed as an attribute to the add_swagger_documentation method. Example

add_swagger_documentation base_path: "/api", api_version: "v1"
